version: "3"
services:
  inginx:
    container_name: "nginx"
    build:
      context: ./docker/nginx
    depends_on:
      - app
    ports:
      - 80:80
    volumes:
      - ./src:/src
      - ./docker/nginx/logs:/logs

  app:
    container_name: app
    build:
      context: ./docker/app
    depends_on:
      - mysql
    volumes:
      - ./src:/src
      - ./docker/app/php.ini:/usr/local/etc/app/php.ini

  mysql:
    container_name: db
    image: mysql:8.0
    environment:
      MYSQL_DATABASE:
      MYSQL_ROOT_PASSWORD: root
    platform: linux/amd64
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - 3306:3306

  redis:
    image: redis:alpine
    container_name: "redis"
    ports:
      - 16379:6379
