version: "3"
services:
  crm-nginx:
    container_name: "crm-nginx"
    build:
      context: ./docker/nginx
    depends_on:
      - crm-app
    ports:
      - 80:80
    volumes:
      - ./src:/src
      - ./docker/nginx/logs:/logs

  crm-app:
    container_name: "crm-app"
    build:
      context: ./docker/app
    depends_on:
      - crm-mysql
    volumes:
      - ./src:/src
      - ./docker/app/php.ini:/usr/local/etc/app/php.ini

  crm-mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE:
      MYSQL_ROOT_PASSWORD: root
    platform: linux/amd64
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - 3306:3306

  crm-redis:
    image: redis:alpine
    container_name: "crm-redis"
    ports:
      - 16379:6379
